[package]
name = "typed-builder"
description = "Compile-time type-checked builder derive"
version = "0.1.1"
authors = ["IdanArye <idanarye@gmail.com>"]
license = "MIT"
repository = "https://github.com/idanarye/rust-typed-builder"
documentation = "https://idanarye.github.io/rust-typed-builder/"
readme = "README.md"
keywords = ["builder"]

[lib]
proc-macro = true

[dependencies]
syn = {version = "0.15.21", features = ["full", "extra-traits"]}
quote = "0.6.9"
proc-macro2 = "0.4.20"
