[package]
name = "typed-builder"
description = "Compile-time type-checked builder derive"
version = "0.3.0"
authors = ["IdanArye <idanarye@gmail.com>", "Chris Morgan <me@chrismorgan.info>"]
license = "MIT"
repository = "https://github.com/idanarye/rust-typed-builder"
documentation = "https://idanarye.github.io/rust-typed-builder/"
readme = "README.md"
keywords = ["builder"]
categories = ["rust-patterns"]

[lib]
proc-macro = true

[dependencies]
syn = {version = "0.15.26", features = ["full", "extra-traits"]}
quote = "0.6.11"
proc-macro2 = "0.4.27"
